one dimensional array (row)

In [1]:
import numpy as np

arr_1D = np.array([1,2,3,4,5])
print(arr_1D)

[1 2 3 4 5]


two dimensional array (row X column)

In [2]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


multi-dimensional array (3D, 4D, .. nD)

In [3]:
arr_3D = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[10,11,12],
                    [13,14,15],
                    [16,17,18]]])

print(arr_3D)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


#### Various ways to create numpy arrays

In [4]:
arr1 = np.array([1,2,3,4,5])  #* 1D array
arr2 = np.array([[1,2,3], [4,5,6]])  #* 2D array

print(f'1D array: {arr1}')
print(f'2D array: {arr2}')
print(f'array filled with zeros: {np.zeros((3,3))}')
print(f'array filled with ones: {np.ones((2,4))}')
print(f'array filled with default value: {np.full((4,4), 9)}')
print(f'identity matrix of size 4x4: {np.eye(4)}')
print(f'similar to range in Python: {np.arange(1, 20, 2)}')
print(f'generate speficic number of values between 2 numbers: {np.linspace(0, 1, 5)}')

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]
array filled with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array filled with ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array filled with default value: [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
identity matrix of size 4x4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
similar to range in Python: [ 1  3  5  7  9 11 13 15 17 19]
generate speficic number of values between 2 numbers: [0.   0.25 0.5  0.75 1.  ]


#### Array Properties

In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print(f'Shape: {arr.shape}')
print(f'Size: {arr.size}')
print(f'Dimensions: {arr.ndim}')
print(f'Datatypes: {arr.dtype}')
print(f'Size in bytes: {arr.nbytes}')
print(f'arrays transpose: {arr.T}')

Shape: (2, 3)
Size: 6
Dimensions: 2
Datatypes: int64
Size in bytes: 48
arrays transpose: [[10 40]
 [20 50]
 [30 60]]


#### Changing Data Types

In [11]:
arr = np.array([1,2,3], dtype=float)  # Explicit type
print(arr.dtype)

arr_int = arr.astype(np.int32)
print(arr_int.dtype)

float64
int32


#### Reshaping and Flattening arrays

In [14]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped)

flattened = arr.flatten()
print(flattened)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
