#### Indexing and Slicing
---

##### Indexing (Same as Python lists)

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[1])

10
20


---

##### Slicing (Extracting Parts of an array)

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])   # Slice from index 1 to 3
print(arr[:3])    # Slice from index 0 to 2
print(arr[2:])    # Slice from index 2 till the end

[20 30 40]
[10 20 30]
[30 40 50]


**Slicing returns a view, not a copy! Changes affect the original array.**
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

*Why does this happen?*
- Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
- Performance: Enables faster access and manipulation of large datasets without duplicating data.

In [3]:
sliced = arr[1:4]

sliced[0] = 999
print(arr)

[ 10 999  30  40  50]


Use `.copy()` if you need an independent copy.

---

#### Fancy Indexing and Boolean Masking
---

##### Fancy Indexing (Select Multiple Elements)

In [4]:
arr = np.array([1,2,3,4,5])
idx = [0, 2, 4]
print(arr[idx])

[1 3 5]


---

##### Boolean Masking (Fileter Data)

In [7]:
arr = np.array([2,4,6,8,10])
mask = arr > 5  #* Condition: values greater than 5
print(arr[mask])

[ 6  8 10]


This is a powerful way to filter large datasets efficiently!