Built in Mathematical Functions in NumPy

---

In [1]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


1. `np.mean()` - Compute the mean (average) of an array.

In [2]:
np.mean(arr1)

np.float64(2.0)

2. `np.std()` - Compute the standard deviation of an array.

In [3]:
np.std(arr1)

np.float64(0.816496580927726)

3. `np.var()` - Compute the variance of an array.

In [4]:
np.var(arr1)

np.float64(0.6666666666666666)

4. `np.min()` - Compute the minimun value of an array.

In [5]:
np.min(arr1)

np.int64(1)

5. `np.max()` - Compute the maximum value of an array.

In [6]:
np.max(arr1)

np.int64(3)

6. `np.sum()` - Compute the sum of all elements in an array.

In [7]:
np.sum(arr1)

np.int64(6)

7. `np.prod()` - Compute the product of all elements in an array.

In [8]:
np.prod(arr1)

np.int64(6)

8. `np.median()` - Compute the median of an array

In [9]:
np.median(arr1)

np.float64(2.0)

9. `np.percentile()` - Compute the percentile of an array.

In [10]:
np.percentile(arr1, 50)   #* For the 50th percentile (median)

np.float64(2.0)

10. `np.argmin()` - Returns the index of the minimum value in an array.

In [11]:
np.argmin(arr1)

np.int64(0)

11. `np.argmax()` - Returns the index of the maximum value in an array.

In [12]:
np.argmax(arr1)

np.int64(2)

12. `np.corrcoef()` - Compute the correlation coefficient matrix of two arrays.

In [13]:
np.corrcoef(arr1, arr2)

array([[1., 1.],
       [1., 1.]])

13. `np.unique()` - Find the unique elements in an array.

In [14]:
np.unique(arr1)

array([1, 2, 3])

14. `np.diff()` - Compute the n-th differences of an array.

In [15]:
np.diff(arr1)

array([1, 1])

15. `np.cumsum()` - Compute the cumulative sum of an array.

In [16]:
np.cumsum(arr1)

array([1, 3, 6])

16. `np.log()` - Compute the natural logarithm of an array.

In [17]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])

17. `np.exp()` - Compute the exponential of an array.

In [18]:
np.exp(arr1)

array([ 2.71828183,  7.3890561 , 20.08553692])