#### Insert element in array
- `np.insert(arr, index, value, axis=None)`

Note: that array manipulation operations like insert, delete, concat,append does not change the original array. rather they return a new array.

In [10]:
import numpy as np

# In 1D array
arr = np.array([10, 20, 30, 40, 50])
new_arr =np.insert(arr, 2, 25)
print(new_arr)

# In 2D array
arr2D = np.array([[1,2,3],
                  [4,5,6]])
new_arr2D = np.insert(arr2D, 1, [4,5,6], axis=0)
print(new_arr2D)

[10 20 25 30 40 50]
[[1 2 3]
 [4 5 6]
 [4 5 6]]


---

#### Append element in array
- `np.append(arr, value, axis=None)` : append element at the end of the array. Returns an new array without changing the existing one.

In [12]:
arr = np.array(([1,2,3]))
new_arr = np.append(arr, [4,5,6])
print(new_arr)

[1 2 3 4 5 6]


---

Concatenate two arrays
- `np.concatenate((arr1, arr2), axis=0)` : Combine 2 arrays

Here, 

axis 0 > vertical stacking

axis 1 > horizontal stacking

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.concatenate((arr1, arr2), axis=0)
print(new_arr)

[1 2 3 4 5 6]


---

Remove elements from array
- `np.delete(arr, index, axis=0)`: delete array elements at specific index. Returns a new array does not change the old array.

In [23]:
# For 1D array
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.delete(arr, (2))
print(new_arr)

# For 2D array
arr2D = np.array([[10, 20, 30],
                  [40, 50, 60]])
new_arr2D = np.delete(arr2D, 1, axis=1)
print(new_arr2D)

[10 20 40 50]
[[10 30]
 [40 60]]


---

Stacking arrays
- `np.vstack((arr1, arr2))`
- `np.hstack((arr1, arr2))`

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


---

Splitting arrays
- `np.split(arr, split_size)` : split array in equal parts
- `np.vsplit(arr, split_size)` : split array vertically
- `np.hsplit(arr, split_size)` : split array horizontally

In [33]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr_2D = np.array([[1,2,3],
                   [4,5,6]])

print(np.split(arr, 2))
print(np.vsplit(arr_2D, 2))
print(np.hsplit(arr_2D, 3))

[array([10, 20, 30]), array([40, 50, 60])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
