In [1]:
# Assignment 1
#* Create a NumPy array of shape (5,5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

arr = np.random.randint(1, 20, (5,5))
arr[:, 2:3] = 1
print(arr)

[[ 8 14  1  6 11]
 [ 1  6  1  3  9]
 [13 19  1 16  2]
 [19  1  1  7 18]
 [ 1  8  1  4 13]]


In [2]:
#* Create a NumPy array of shape (4,4) with values from1 to 16. Replace the diagonal elements with 0.

np.random.seed(42)
arr = np.random.randint(1, 16, (4,4))
print(arr)
arr[0,0] = 0
arr[1,1] = 0
arr[2,2] = 0
arr[3,3] = 0
print(arr)

[[ 7  4 13 15]
 [11  8 13  5]
 [ 7 10  3  7]
 [11 11  8  5]]
[[ 0  4 13 15]
 [11  0 13  5]
 [ 7 10  0  7]
 [11 11  8  0]]


In [3]:
# Assignment 2
#* Create a NumPy array of shape (6,6) with values from 1 to 36. Extract the sub-array consisting of 3rd and 5th rows and 2nd and 4th columns.
np.random.seed(42)
arr = np.random.randint(1, 36, (6,6))
print(arr)
print(arr[2:5, 1:4])

[[29 15  8 21 19 23]
 [11 11 24 24  3 22]
 [ 2 24 30  2 21 33]
 [12 22 25 27 28 16]
 [15  3  7 21  9 18]
 [ 4 25 14  9 26  2]]
[[24 30  2]
 [22 25 27]
 [ 3  7 21]]


In [4]:
#* Create a NumPy array of shape (5,5) with random integers. Extract elements on the border.

np.random.seed(42)
arr = np.random.randint(1, 25, (5,5))
print(arr)

# Extract border elements 
border = np.concatenate([
    arr[0, :],       #* top row
    arr[1:-1, -1],    #* right row
    arr[-1, ::-1],     #* bottom row
    arr[-2:0:-1, 0]   #* left column
]) 
print(border)

[[ 7 20 15 11  8]
 [21  7 19 23 11]
 [11 24 21  4  8]
 [24  3 22 21  2]
 [24 12  6  2 21]]
[ 7 20 15 11  8 11  8  2 21  2  6 12 24 24 11 21]


In [5]:
# Assignment 3
#* Create two NumPy arrays of shape (3,4) filled with random integers. Perform element wise addition, substraction, multiplication, division.

arr1 = np.random.randint(1, 10, (3,4))
arr2 = np.random.randint(1, 10, (3,4))

print(f'Addition:\n {arr1 + arr2}')
print(f'Substraction:\n {arr1 - arr2}')
print(f'Multiplication:\n {arr1 * arr2}')
print(f'Division:\n {arr1 / arr2}')

Addition:
 [[ 6 15 16  3]
 [ 7 16  6 18]
 [ 8  7  7 14]]
Substraction:
 [[-4 -3  2 -1]
 [-1 -2  2  0]
 [-2  3 -1  0]]
Multiplication:
 [[ 5 54 63  2]
 [12 63  8 81]
 [15 10 12 49]]
Division:
 [[0.2        0.66666667 1.28571429 0.5       ]
 [0.75       0.77777778 2.         1.        ]
 [0.6        2.5        0.75       1.        ]]


In [6]:
#* Create a NumPy array of shape (4,4) with values from 1 to 16. compute the row-wise and column-wise sum

np.random.seed(42)
arr = np.random.randint(1, 16, (4,4))
print(arr)

print(f' Row-wise sum: \n {np.sum(arr, axis=0)}')
print(f'Column-wise sum:\n {np.sum(arr, axis=1)}')

[[ 7  4 13 15]
 [11  8 13  5]
 [ 7 10  3  7]
 [11 11  8  5]]
 Row-wise sum: 
 [36 33 37 32]
Column-wise sum:
 [39 37 27 35]


In [7]:
# Assignment 4
#* Create a NumPy array of shape (5,5) filled with random integers. Compute the mean, median, standard deviation and variance of the array.

arr = np.random.randint(1, 25, (5,5))
print(f'Mean: {np.mean(arr)}')
print(f'Median: {np.median(arr)}')
print(f'Standard Deviation: {np.std(arr)}')
print(f'Variance: {np.var(arr)}')

Mean: 13.72
Median: 15.0
Standard Deviation: 7.459329728601626
Variance: 55.6416


In [8]:
#* Create a NumPy array of shape (3,3) with values from 1 t0 9. Normalize the array (i.e scale the values to have mean of 0 and standard deviation of 1)

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
mean = np.mean(arr)
std = np.std(arr)

normalized_data = (arr - mean) / std
print(normalized_data)


[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [9]:
# Assignment 5
#* Create a NumPy array of shape (3,3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting

np.random.seed(42)
arr = np.random.randint(1,9, (3,3))
arr1D = np.random.randint(1,3, (3,))

print(arr)
print(arr1D)

print(f'Broadcast 1D to 2D:\n {arr + arr1D}')

[[7 4 5]
 [7 3 8]
 [5 5 7]]
[2 1 1]
Broadcast 1D to 2D:
 [[9 5 6]
 [9 4 9]
 [7 6 8]]


In [10]:
#* Create a NumPy array of shape (4,4) filled with random integers. Substract a 1D array of shape (4,) from each column of the 2D array using broadcasting

np.random.seed(42)
arr_1D = np.random.randint(1,4, (4,))
arr_2D = np.random.randint(1,16, (4,4))

print(arr_1D)
print(arr_2D)

print(f'Sunstracting 1D from 2D:\n {arr_2D - arr_1D}')

[3 1 3 3]
[[ 8 13  5  7]
 [10  3  7 11]
 [11  8  5  4]
 [ 8  8  3  6]]
Sunstracting 1D from 2D:
 [[ 5 12  2  4]
 [ 7  2  4  8]
 [ 8  7  2  1]
 [ 5  7  0  3]]


In [11]:
# Assignment 6
#* Create a NumPy array of shape (3,3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

arr = np.array([[1,2,3],
                [4,17,6],
                [7,37,9]])

#* 1. Determinant
det = np.linalg.det(arr)
print(f'Determinant: {det}')

#* 2. inverse
inv = np.linalg.inv(arr)
print(f'Inverse:\n {inv}')

#* 3. eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr)
print(f'Eigenvalues:\n {eigenvalues}')
print(f'Eigenvectors:\n {eigenvectors}')

Determinant: 29.999999999999975
Inverse:
 [[-2.3         3.1        -1.3       ]
 [ 0.2        -0.4         0.2       ]
 [ 0.96666667 -0.76666667  0.3       ]]
Eigenvalues:
 [29.47710046 -0.52003266 -1.9570678 ]
Eigenvectors:
 [[-0.12494946 -0.90683126 -0.67987393]
 [-0.46222905  0.06438585 -0.08700709]
 [-0.8779134   0.41654715  0.72814916]]


In [12]:
#* Create a NumPy arrays of shape (2,3) and (3,2). Perform matrix multiplication on these arrays

arr1 = np.random.randint(1,5, (2,3))
arr2 = np.random.randint(1,5, (3,2))

matrix_mul = np.dot(arr1, arr2)
print(f'Array 1: \n {arr1}')
print(f'Array 2: \n {arr2}')
print(f'Multiplication:\n {matrix_mul}')

Array 1: 
 [[1 2 4]
 [4 2 2]]
Array 2: 
 [[2 4]
 [4 1]
 [1 4]]
Multiplication:
 [[14 22]
 [18 26]]


In [13]:
# Assignment 7
#* Create a NumPy array of shape (3,3) with values 1 to 9. Reshape the array to shape (1, 9) and then to shape (9,1)

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

reshape1 = np.reshape(arr, (1,9))
print(reshape1)

reshape2 = np.reshape(arr, (9,1))
print(reshape2)

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [14]:
#* Create a NumPy array of shape (5,5) filled with random integers. Flatten the array and then reshape it back to (5,5)

arr = np.random.randint(1, 25, (5,5))

flatten = arr.flatten()
reshape = np.reshape(flatten, (5,5))

print(reshape)

[[22 12 17 10 16]
 [15 15 19 12 23]
 [20  3  5 19  7]
 [21  9  7 18  4]
 [14 18  9 21  2]]


In [15]:
# Assignment 8
#* Create a NumPy array of shape (5,5) filled with random integers. Use fancy indexing to extract the elements at the corner of the array.

np.random.seed(42)
arr = np.random.randint(1, 25, (5,5))
print(arr)

corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print(corners)

[[ 7 20 15 11  8]
 [21  7 19 23 11]
 [11 24 21  4  8]
 [24  3 22 21  2]
 [24 12  6  2 21]]
[ 7  8 24 21]


In [16]:
#* Create a NumPy array of shape (4,4) filled with random integers. use boolean masking to set all elements greater than 10 to 10.
np.random.seed(42)
arr = np.random.randint(1, 16, (4,4))
print(arr)

arr[arr>10] = 10
print(arr)

[[ 7  4 13 15]
 [11  8 13  5]
 [ 7 10  3  7]
 [11 11  8  5]]
[[ 7  4 10 10]
 [10  8 10  5]
 [ 7 10  3  7]
 [10 10  8  5]]


In [17]:
# Assignment 9
#* Create a structured array with fields 'name' (string), 'age' (integer), 'weight' (float). Add some data and sort the array by age.

student_dtype = np.dtype([
    ('name', 'U10'),
    ('age', 'i4'),
    ('weight', 'f4')
])

structuted_array = np.array([
    ('Alice', 18, 45.0),
    ('Bob', 17, 40),
    ('Charlie', 30, 56.7)
], dtype=student_dtype)

sorted_students = np.sort(structuted_array, order='age')
print(sorted_students)

[('Bob', 17, 40. ) ('Alice', 18, 45. ) ('Charlie', 30, 56.7)]


In [18]:
#* Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

data_dtype = np.dtype([
    ('x', 'i4'),
    ('y', 'i4')
])

data = np.array([
    (1, 7),
    (9, 3), 
    (4, 7), 
    (3, 9)
], dtype=data_dtype)

print(data)


# Extract coordinates as normal 2D NumPy array
coords = np.column_stack((data['x'], data['y']))

# Compute pairwise Euclidean distances
diff = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
distances = np.sqrt(np.sum(diff**2, axis=-1))

print("\nPairwise Euclidean Distance Matrix:\n", distances)

[(1, 7) (9, 3) (4, 7) (3, 9)]

Pairwise Euclidean Distance Matrix:
 [[0.         8.94427191 3.         2.82842712]
 [8.94427191 0.         6.40312424 8.48528137]
 [3.         6.40312424 0.         2.23606798]
 [2.82842712 8.48528137 2.23606798 0.        ]]


In [19]:
# Assignment 10
#* Create a masked array of shape (4,4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

data = np.random.randint(0, 20, (4,4))
print(f'Original Array: \n{data}')

#* mask the elements greater than 10
masked_arr = np.ma.masked_greater(data, 10)
print(f'\nMasked Array: \n{masked_arr}')

#* Compute the sum of unmasked elements
sum_unmasked = masked_arr.sum()
print(f'Sum of unmasked elements: \n', sum_unmasked)

Original Array: 
[[ 3  7  2  1]
 [11  5  1  0]
 [11 11 16  9]
 [15 14 14 18]]

Masked Array: 
[[3 7 2 1]
 [-- 5 1 0]
 [-- -- -- 9]
 [-- -- -- --]]
Sum of unmasked elements: 
 28


In [20]:
#* Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

data = np.random.randint(1, 16, (3,3))
print(f'Original Array: \n {data}')

# mark the diagonal elements
masked_arr = np.ma.array(data, mask=np.eye(3, dtype=bool))
print(f'Masked Array (diagonal masked):\n {masked_arr}')

# Compute the mean of unmasked elements
mean_unmasked = masked_arr.mean()
print(f'Mean of unmasked elements: {mean_unmasked}')

# Replace masked elements with the mean
filled_arr = masked_arr.filled(mean_unmasked)
print(f'Array after replacing maasked (diagonal) elements with mean: \n {filled_arr}')

Original Array: 
 [[12  7  4]
 [ 9  3  5]
 [ 3  7  5]]
Masked Array (diagonal masked):
 [[-- 7 4]
 [9 -- 5]
 [3 7 --]]
Mean of unmasked elements: 5.833333333333333
Array after replacing maasked (diagonal) elements with mean: 
 [[5 7 4]
 [9 5 5]
 [3 7 5]]
