#### NumPy and Pandas (Easy)

---

##### Assignment 1: NumPy Array Creation

1. Create a NumPy array of 10 integers from 0 to 9. Print the array and its data types.

In [1]:
import numpy as np

arr = np.random.randint(0, 9, (10,))
print(arr)
print(arr.dtype)

[0 2 0 8 0 8 1 5 8 8]
int32


2. Create a Numpy array of shape (3,3) filled with zeros.

In [2]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

##### Assignment 2: NumPy Array Operations

1. Create a NumPy array with values from 1 to 5. Print the array and its data types.

In [3]:
arr = np.arange(1, 6)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


2. Create 2 NumPy arrays of length 5 and perform element-wise addition.

In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
result = arr1 + arr2
print(result)

[ 2  4  6  8 10]


---

##### Assignment 3: NumPy Indexing and Slicing

1. Create a NumPy array with values from 10 to 50. Extract elements from index 2 to 5.

In [5]:
arr = np.arange(10, 51)
extract = arr[2:6]

print(arr)
print(extract)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[12 13 14 15]


2. Create a NumPy array of shape (3,3) and access the element in the second row and third column.

In [6]:
arr = np.random.randint(1, 10, (3,3))
print(arr)
print(arr[1:2, 2:3])

[[7 4 5]
 [1 6 6]
 [1 5 5]]
[[6]]


---

##### Assignment 4: NumPy Statistical Functions

1. Create a NumPy array of 8 random integers between 1 and 20. Find the mean and maximum value.

In [7]:
arr = np.random.randint(1,20, (8,))

print(arr)
print(f'Mean: {np.mean(arr)}')
print(f'Maximum Value: {np.max(arr)}')

[12 13  9  9  3  4 12 18]
Mean: 10.0
Maximum Value: 18


2. Create a NumPy array and calculate the sum of all elements.

In [8]:
arr = np.array([1,2,3,4,5])

print(arr)
print(f'Sum of all elements: {np.sum(arr)}')

[1 2 3 4 5]
Sum of all elements: 15


---

##### Assignment 5: NumPy Reshaping

1. Create a NumPy array of 12 elements and reshape it into (3,4) array.

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(f'Old Array : {arr}')
print(f'New Reshaped Array:\n {arr.reshape(3,4)}')

Old Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
New Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Create a NumPy array of shape (2,5) and flatten it into a 1D array.

In [11]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5]])

print(f'Old Array:\n {arr}')
print(f'New Flatten Array: {arr.flatten()}')

Old Array:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
New Flatten Array: [1 2 3 4 5 1 2 3 4 5]


---

##### Assignment 6: Pandas Series Basics

1. Create a Pandas Series from a list of integers and display it.

In [13]:
import pandas as pd

numbers_list = [1,2,3,4,5]

series = pd.Series(numbers_list)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


2. Create a Pandas Series with custom index labels and access one element using its label.

In [15]:
series = pd.Series([1,2,3,4,5], index=['A', 'B', 'C', 'D', 'E'])
print(series['A'])

1


---

##### Assignment 7: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [24]:
data = np.random.randint(1, 10, (6, 4))
index = data[:, 0:1].flatten()
df = pd.DataFrame(data, index=index)
print(data)
df

[[5 2 2 1]
 [4 6 6 7]
 [1 3 3 7]
 [2 1 4 1]
 [1 1 9 5]
 [1 9 9 8]]


0  1  2  3
5  5  2  2  1
4  4  6  6  7
1  1  3  3  7
2  2  1  4  1
1  1  1  9  5
1  1  9  9  8

2. Create a Pandas DataFrame with columns `'A'`, `'B'`, `'C'`, and, `'X'`, `'Y'`, `'Z'`. Fill it with random integers and access the element at row 'Y' and column 'B'.

In [26]:
data = np.random.randint(1, 10, (3,3))
columns = ['A', 'B', 'C']
index = ['X', 'Y', 'Z']

df = pd.DataFrame(data, columns=columns, index=index)
print(df)
print(df.loc['Y', 'B'])

   A  B  C
X  5  1  5
Y  3  1  8
Z  1  5  1
1


---

##### Assignment 8: DataFrame column Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new colum that is the sum of the first two columns.

2. Rename 1 column in the DataFrame and display the DataFrame.

In [41]:
data = np.random.randint(1, 5, (5, 3))

df = pd.DataFrame(data, columns=['A', 'B', 'C'])

print(df)
df['A_B'] = df['A'] + df['B']
print(df)

df.rename(columns={'C': 'D'}, inplace=True)

print(df)

   A  B  C
0  3  1  2
1  3  4  4
2  3  2  1
3  1  3  4
4  2  4  1
   A  B  C  A_B
0  3  1  2    4
1  3  4  4    7
2  3  2  1    5
3  1  3  4    4
4  2  4  1    6
   A  B  D  A_B
0  3  1  2    4
1  3  4  4    7
2  3  2  1    5
3  1  3  4    4
4  2  4  1    6


---

##### Assignment 9: DataFrame Row and Column Selection

1. Create and Pandas DataFrame and select only one column using column indexing.

In [46]:
df = pd.DataFrame(np.random.randint(1, 9, (3,3)), columns=['A', 'B', 'C'])

print(df)

# select only one column
print(df.loc[:, 'A'])

   A  B  C
0  7  2  7
1  5  5  6
2  8  3  1
0    7
1    5
2    8
Name: A, dtype: int32


2. Select the first 2 rows of the DataFrame using `iloc`.

In [52]:
print(df)
print("------------------")
print(df.iloc[0:2, :])

   A  B  C
0  7  2  7
1  5  5  6
2  8  3  1
------------------
   A  B  C
0  7  2  7
1  5  5  6


---

##### Assignment 11: Handling Missing Values

1. Create a Pandas DataFrame with some missing (`NaN`) values. Detect the missing values.

2. Fill the missing values with zero.

In [55]:
df = pd.DataFrame({
    'name':["Prince", None, 'Shambhu', "Prashant"],
    'age': [20, 21, 22, None]
})

# detect null values
df.isnull()

# Fill missing values with zero
df.fillna(0)

name   age
0    Prince  20.0
1         0  21.0
2   Shambhu  22.0
3  Prashant   0.0

---

##### Assignment 12: DataFrame Filtering

1. Create a Pandas DataFrame with one column named `Marks`. Filter rows where marks are greate than 50.

2. Filter rows where marks are less than or equal to 50.

In [58]:
df = pd.DataFrame(np.random.randint(1, 100, (20,)), columns=['Marks'])

# Filter rows where marks > 50
print('Marks Greater than 50: ')
print(df[df["Marks"] > 50])
print("-----------------------")

# Filter rows where marks <= 50
print('Marks Greater than or equal to 50: ')
print(df[df['Marks'] <= 50])

Marks Greater than 50: 
    Marks
1      52
2      96
3      89
4      66
5      73
6      90
7      60
9      68
10     67
11     85
12     56
13     54
-----------------------
Marks Greater than or equal to 50: 
    Marks
0      25
8      42
14     39
15     46
16     37
17     27
18     42
19     35


---

##### Assignment 13: Sorting Data

1. Create a Pandas DataFrame and sort it based on one column.

2. Sort the same DataFrame in descending order.

In [ ]:
df = pd.DataFrame(np.random.randint(30, 90, (40,)), columns=['Sort'])

# sort it based on column 'Sort'
df['Sort'].sort_values()

# Sort in descending order

df['Sort'].sort_values(ascending=False)

37    89
26    86
31    86
0     84
22    83
18    81
9     79
16    78
15    76
17    75
4     75
35    74
3     71
5     70
13    69
10    66
2     63
30    61
7     60
34    60
23    59
12    57
1     55
33    52
29    51
28    50
11    49
14    48
19    48
6     47
27    43
38    40
8     39
20    39
25    38
21    36
32    33
24    32
39    32
36    31
Name: Sort, dtype: int32

---

##### Assignment 14: Basic GroupBy

1. Create a Pandas DataFrame with columns `'Department'` and `'Salary'`. Group the data by department and calculate the mean salary.

2. Count the number of employees in each department.

In [66]:
df = pd.DataFrame({
    "Department": ["IT", "CS", "IT", "Medicine", "CS"],
    "Salary": [32000, 54000, 32800, 54800,48000]
})

# Group by department and mean salary
avg_salary = df.groupby('Department')['Salary'].mean()
print(avg_salary)

# Count the number of employees in each deparment
count =  df.groupby('Department')['Salary'].count()
print(count)

Department
CS          51000.0
IT          32400.0
Medicine    54800.0
Name: Salary, dtype: float64
Department
CS          2
IT          2
Medicine    1
Name: Salary, dtype: int64


---

##### Assignment 15: NumPy and Pandas Integration

1. Create a NumPy array of shape (5,5) with random integers and convert it into a Pandas DataFrame.

2. Assign column names to the DataFrame and display first three roes.

In [68]:
df = pd.DataFrame(np.random.randint(1, 10, (5,5)), columns=['A', 'B', 'C', 'D', 'E'])

print(df)
print("-------------")
# display first three rows
df.iloc[0:3, :]

   A  B  C  D  E
0  5  6  2  2  7
1  2  3  8  8  9
2  7  5  3  2  5
3  4  6  1  8  7
4  7  4  7  1  1
-------------


A  B  C  D  E
0  5  6  2  2  7
1  2  3  8  8  9
2  7  5  3  2  5