Following the structure of your previous assignments, here is a set of 15 practice questions focused on **NumPy**. This covers array creation, indexing, mathematical operations, and statistical analysis.

---

## Python Part 3: NumPy Basics & Beyond

### Assignment 1: Array Initialization

1. Create a 1D NumPy array with elements from 10 to 20.
2. Create a 3x3 matrix containing only zeros.

---

### Assignment 2: Array Properties

1. Create a 2D array and print its **shape**, **size**, and **data type**.
2. Convert an existing list of floats into a NumPy array with an `int32` data type.

---

### Assignment 3: Slicing and Indexing

1. Create a 4x4 matrix and extract the inner 2x2 sub-array.
2. Use boolean indexing to select all elements greater than 50 from a random array of 10 elements.

---

### Assignment 4: Universal Functions (ufuncs)

1. Create an array of angles in degrees () and calculate their sine values.
2. Perform element-wise addition and multiplication on two arrays of the same shape.

---

### Assignment 5: Reshaping and Transposing

1. Flatten a 3x3 matrix into a 1D array of 9 elements.
2. Create a 2x3 array and reshape it into a 3x2 array. Print the transpose of the original array to see the difference.

---

### Assignment 6: Random Module

1. Generate a 5x5 matrix of random floats sampled from a **standard normal distribution**.
2. Create an array of 10 random integers between 100 and 500.

---

### Assignment 7: Statistical Operations

1. Find the **mean**, **median**, and **standard deviation** of a 1D array of 20 random numbers.
2. Create a 2D array and find the maximum value along **axis 0** (columns).

---

### Assignment 8: Broadcasting Rules

1. Add a 1D array of shape `(3,)` to a 2D array of shape `(3,3)`.
2. Explain in a comment the condition required for two arrays to be "broadcast-compatible."

---

### Assignment 9: Array Manipulation

1. Use `np.vstack()` and `np.hstack()` to combine two 2x2 matrices vertically and horizontally.
2. Split a 1D array of 12 elements into three equal parts using `np.split()`.

---

### Assignment 10: Searching and Sorting

1. Use `np.where()` to find the indices of all even numbers in an array.
2. Sort a 2D array such that each row is sorted in ascending order.

---

### Assignment 11: Linear Algebra Basics

1. Perform a **dot product** between a 2x3 matrix and a 3x2 matrix.
2. Calculate the **identity matrix** of size 4x4.

---

### Assignment 12: Aggregate Functions

1. Create an array with some `NaN` (Not a Number) values.
2. Use a NumPy function to calculate the sum of the array while ignoring the `NaN` values.

---

### Assignment 13: Memory Efficiency (NumPy vs List)

1. Write a script that compares the time taken to add 1 million elements in a Python list vs. a NumPy array.
2. Use the `time` module to display the difference in execution speed.

---

### Assignment 14: Filtering and Constraints

1. Create an array of numbers from 1 to 30.
2. Replace all multiples of 3 with the value `-1` without using a `for` loop.

---

### Assignment 15: File I/O with NumPy

1. Save a NumPy array to a file named `data.npy` using `np.save()`.
2. Load the array back into a new variable using `np.load()` and verify the content.

---

**Would you like me to generate the code cells for these questions so you can test them out, or shall we move on to Pandas?**

##### Assignment 1: Array Initialization

1. Create a 1D NumPy array with elements from 10 to 20.

In [1]:
import numpy as np

arr_1D = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])
print(arr_1D)

[10 11 12 13 14 15 16 17 18 19 20 21]


2. Create a 3X3 matrix containing only zeros

In [2]:
arr_3D = np.zeros((3,3))
print(arr_3D)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

##### Assignment 2: Array Properties

1. Create a 2D array and print its shape, size, and data type.

In [3]:
arr_2D = np.array([[1,2,3,4],
                   [5,6,7,8]])

print(arr_2D.size)
print(arr_2D.shape)
print(arr_2D.dtype)

8
(2, 4)
int64


2. Convert an existing list of floats into numpy array with an `int32` datatype.

In [4]:
arr_list = [1.2, 3.4, 5.6, 7.8, 9.1]

int_arr = np.array(arr_list, dtype='int32')

print(arr_list)
print(int_arr)

[1.2, 3.4, 5.6, 7.8, 9.1]
[1 3 5 7 9]


---

##### Assignment 3: Slicing and Indexing

1. Create a 4x4 matrix and extract the inner 2x2 sub-array.

In [5]:
arr_4D = np.random.randint(1, 10, (4,4))

print(arr_4D)
print(arr_4D[1:3, 1:3])

[[7 8 7 7]
 [3 1 7 2]
 [8 6 6 3]
 [2 7 6 9]]
[[1 7]
 [6 6]]


2. Use boolean indexing to select all the elements greater than 50 from a random array of 10 elements.

In [6]:
arr = np.array([10, 21,3, 4, 100, 26, 9, 28, 55, 28])

great10 = arr > 50
print(great10)

[False False False False  True False False False  True False]


---

##### Assignment 4: Universal Functions

1. Create an array of angles in degrees () and calculate their sine values.

In [7]:
arr = np.degrees([10, 20, 30, 90, 180, 27, 360])

sin = np.sin(arr)
print(sin)

[ 0.92759846  0.6930622  -0.4097718  -0.95409147  0.57153017  0.969323
 -0.93797365]


2. Perform element-wise addition and multiplication on two arrays of the same shape.

In [8]:
arr1 = np.random.randint(10, 20, (4,4))
arr2 = np.random.randint(10, 20, (4,4))

print(arr1)
print(arr2)

addition = arr1 + arr2
multiplication = arr1 + arr2

print(addition)
print(multiplication)

[[19 13 18 13]
 [19 11 12 15]
 [15 18 11 18]
 [12 12 12 17]]
[[19 19 18 18]
 [16 14 10 10]
 [15 17 17 13]
 [13 11 10 19]]
[[38 32 36 31]
 [35 25 22 25]
 [30 35 28 31]
 [25 23 22 36]]
[[38 32 36 31]
 [35 25 22 25]
 [30 35 28 31]
 [25 23 22 36]]


---

##### Assignment 5: Reshaping and Transposing

1. Flatten a 3x3 matrix into a 1D array of 9 elements.

In [9]:
arr = np.random.randint(1, 9, (3,3))
print(arr)

flat_arr = arr.flatten()
print(flat_arr)

[[4 8 7]
 [4 2 6]
 [3 7 5]]
[4 8 7 4 2 6 3 7 5]


2. Create a 2x3 array and reshape it into a 3x2 array. Print the transpose of the original array to see the difference.

In [10]:
arr = np.random.randint(1, 9, (2,3))

reshaped_arr = np.reshape(arr, (3,2))

print(f"Reshaped Array : {reshaped_arr}")
print(f"Transposed Array: {arr.T}")

Reshaped Array : [[4 6]
 [8 7]
 [4 4]]
Transposed Array: [[4 7]
 [6 4]
 [8 4]]


---

##### Assignment 6: Random Module

1. Generate a 5x5 matrix of random float sampled from standard normal distribution

In [11]:
arr = np.random.normal(1.0, 0.5, (5,5))
print(arr)

[[ 0.86887636  1.80428979  1.63049589  0.56873159  1.07464844]
 [ 0.56329764  0.27503617 -0.86876399  1.22594615  0.56245509]
 [ 1.71664408  1.01459263  1.40922142  1.23610313  0.82861076]
 [ 1.0030416   0.77295368  0.61016319  0.59281325  0.86956247]
 [ 0.36226917  0.83122461  0.9742171   1.54394384  0.64659766]]


2. Create a array of 10 random integers between 100 and 500.

In [12]:
arr = np.random.randint(100, 500, 10)
print(arr)

[417 242 288 228 176 395 418 133 260 150]


---

##### Assignment 7: Statistical Operations

1. Find the mean, median, and standard deviation of a 1D array of 20 random numbers.

In [13]:
arr = np.random.randint(100, 200, 20)

print(arr.mean())
print(np.median(arr))
print(arr.std())

151.35
151.0
33.10630604582758


2. Create a 2D array and find the maximum value along axis 0 (columns)

In [14]:
arr = np.random.randint(1, 10, (2,2))

print(arr)
arr.max(axis=0)

[[3 1]
 [2 4]]


array([3, 4], dtype=int32)

---

##### Assignment 8: Broadcasting Rules

1. Add a 1D array of shape `(3,)` to a 2D array of shape `(3,3)`.

In [15]:
arr = np.array([1, 2, 3])
arr_2D = np.array([[4, 5, 6],
                   [7, 8, 9]])

print(arr + arr_2D)

[[ 5  7  9]
 [ 8 10 12]]


---

##### Assignment 9: Array Manipulation

1. Use `np.vstack()` and `np.hstack()` to combine two 2x2 matrices vertically and horizontally.

In [16]:
arr1 = np.random.randint(10, 20, (2,2))
arr2 = np.random.randint(10, 20, (2,2))


print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[19 15]
 [15 16]
 [15 13]
 [10 14]]
[[19 15 15 13]
 [15 16 10 14]]


2. Split a 1D array of 12 elements into three equal parts using `np.split()`.

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

part1, part2, part3 = np.split(arr, 3)
print(part1)
print(part2)
print(part3)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


##### Assignment 10: Searching and Sorting

1. Use `np.where()` to find the indices of all even numbers in an array.

2. Sort a 2D array such that each row sorted in ascending order.

In [18]:
arr = np.array([[9,8,7],[6,5,4]])
np.sort(arr)

array([[7, 8, 9],
       [4, 5, 6]])

---

##### Assignment 11: Linear Algebra Basics

1. Perform a dot product between 2x3 and 3x2 matrix.

In [19]:
arr1 = np.random.randint(1, 10, (2,3))
arr1 = np.random.randint(1, 10, (3,2))

print(np.dot(arr1, arr2))

[[125 135]
 [ 40  40]
 [155 161]]


2. Calculate the identity matrix of size 4x4.

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

##### Assignment 12: Aggregate Functions

1. Create an array with some `Nan` (Not a Number) values.

In [58]:
arr = np.array([1,2,3,np.nan, np.nan, 5,4])
print(arr)

[ 1.  2.  3. nan nan  5.  4.]


2. Use a NumPy function to calculate the sum of the array while ignoring the `NaN` values.

In [59]:
print(np.nansum(arr))

15.0


---

##### Assignment 13: Memory Efficiency (Numpy vs List)

1. Write a script that compares the time taken to add 1 million elements in a Python list vs. a NumPy array.

2. Use the `time` module to display the difference in execution speed.

In [ ]:
import time

pylist1 = [x for x in range(1000000)]
pylist2 = [x for x in range(1000000)]

start = time.time()
sum_of_lists = pylist1 + pylist2
end = time.time()

print(f'Time taken for a list to add all 1 million elements: {end - start}')


arr1 = np.array(len(pylist1))
arr2 = np.array(len(pylist1))

start = time.time()
sum_of_lists = arr1 + arr2
end = time.time()

print(f'Time taken for a list to add all 1 million elements: {end - start}')


Time taken for a list to add all 1 million elements: 0.03523755073547363
Time taken for a list to add all 1 million elements: 0.010904312133789062


---

##### Assignment 14: Filtering and Constraints

1. Create an array of numbers from 1 to 30.

2. Replace all multiple of 3 with the value `-1` without using `for` loop.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])

mask = arr % 3 == 0
arr[mask] = -1

print(arr)


[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20 -1 22 23 -1
 25 26 -1 28 29 -1]


---

##### Assignment 15: File I/O with NumPy

1. Save a NumPy array to a file named `data.npy` using `np.save()`.

2. Load the array back into a new variable using `np.load()` and verify the content.

In [ ]:
arr = np.random.randint(1, 1000, (1000, 1000))

np.save('data.npy', arr)

confirm = np.load('data.npy', 'r')
print(confirm)

[[367 859 549 ... 678 423 727]
 [691 431 449 ... 598 224 470]
 [649  75 123 ... 141 230 908]
 ...
 [256 979 993 ... 256 528 204]
 [690 584 848 ... 928 422 274]
 [644 607 930 ... 972 872 508]]
