# Inverse of a matrix:

In [ ]:
import numpy as np

A = np.array([[1,3,4],
            [6,4,1],
            [2,2,2]])
B = np.array([5, 16, 11])

print(A)
print(B)


# To calculate A inverse
A_inv = np.linalg.inv(A)
print(A_inv)

# Calculate X from A_inv and B
X = np.dot(A_inv, B)
print('Value of X: ', X)

[[1 3 4]
 [6 4 1]
 [2 2 2]]
[ 5 16 11]
[[-0.75  -0.25   1.625]
 [ 1.25   0.75  -2.875]
 [-0.5   -0.5    1.75 ]]
Value of X:  [ 10.125 -13.375   8.75 ]


So to calculate the solution for any system of linear equations we can use `np.dot(np.linalg.inv(A), B)`